#server:
##  port:8080
##
##spring:
##  redis:
##    host:118.31.66.30
#    password:zhengyuekai
#    port:6378
#    jedis:
#      pool:
#        max-active:10
#        max-idle:6
#        max-wait:5
#        min-idle:2
#    timeout:2000

